export const FETCH_EXCHANGE_RATE_STARTED = 'FETCH_EXCHANGE_RATE STARTED';
export const FETCH_EXCHANGE_RATE_SUCCESS = 'FETCH_EXCHANGE_RATE_SUCCES';
export const FETCH_EXCHANGE_RATE_FAIL = 'FETCH_EXCHANGE_RATE_FAIL';